name: Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROD_VERCEL_PROJECT_ID }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+[0-9]+'
jobs:
  production:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: sed -i '' 's/NEXT_GIT_COMMIT_SHA/${{ github.sha }}/g' next.config.js
      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.CYF_RELEASE_TOKEN }}
